---

- name: Generate ntp configuration file.
  tags:
    - configure_ntp
  template:
    src: "{{ ntp_config_file | basename }}.j2"
    dest: "{{ ntp_config_file }}"
    mode: 0644
  notify: restart ntp
