#!/bin/sh

set -e

. /etc/profile.d/java.sh

DESC=Greengrass
LOGFILE=/var/log/greengrassd.log

PIDFILE=/greengrass/v2/alts/loader.pid

# Full path to executable
DAEMON=/greengrass/v2/alts/current/distro/bin/loader

# Options
DAEMON_OPTS=""

# Default users and group
USER="ggc_user"
GROUP="ggc_group"

if ! [ -x $DAEMON ]; then
  echo "Greengrass Core is not present or not executable!"
  exit 0
fi

start() {
  echo "Starting service $DESC"

  touch "$LOGFILE"
  chgrp $GROUP "$LOGFILE"

  start-stop-daemon -g $GROUP --start --background \
    --pidfile "$PIDFILE" \
    --make-pidfile \
    --quiet \
    --startas /bin/sh \
    -- \
    -c "$DAEMON -p $PIDFILE $DAEMON_OPTS >> $LOGFILE 2>&1"

  echo "$DESC started"
}

stop() {
  if [ -f "$PIDFILE" ]; then
    echo "Stopping service $DESC"
    start-stop-daemon --stop --pidfile "$PIDFILE" --retry 10 --oknodo --remove-pidfile
    echo "$DESC stopped"
  else
    echo "$DESC already stopped - file $PIDFILE not found."
  fi
}

case "$1" in
start)
  start
  ;;
stop)
  stop
  ;;
restart)
  echo "Restarting daemon: $DESC"
  start-stop-daemon --stop --quiet --oknodo --retry 30 --pidfile $PIDFILE
  start
  echo "."
  ;;
status)
  status_of_proc -p $PIDFILE $DAEMON $DESC && exit 0 || exit $?
  ;;
*)
  echo "Usage: $0 {start|stop|restart|status}"
  ;;
esac

exit 0
