---

- name: Install pip python package manager
  tags:
    - install_pip
  block:
  - name: Get installed pip version
    command: "{{ pip_executable }} --version"
    register: pip_version_output
    ignore_errors: yes
    changed_when: false

  - name: Download get-pip.py
    get_url:
      url: 'https://bootstrap.pypa.io/pip/get-pip.py'
      dest: /tmp/get-pip.py
    when: pip_version_output is failed

  # Install pip if it's not already installed
  - name: Install pip
    command: "{{ ansible_python_interpreter if ansible_python_interpreter is defined else 'python' }} get-pip.py"
    when: pip_version_output is failed
    args:
      chdir: /tmp

  - name: Remove get-pip.py
    file:
      path: /tmp/get-pip.py
      state: absent
