---

- name: Install docker
  tags:
    - docker
    - docker_install
  block:
    - name: Populate service facts
      ansible.builtin.service_facts:

    - name: Stop docker service, if running
      ansible.builtin.service:
        name: docker
        state: stopped
      when: ansible_facts.services["docker.service"] is defined and ansible_facts.services["docker.service"].state == "running"

    - name: Download and extract docker binaries
      ansible.builtin.unarchive:
        src: "https://download.docker.com/linux/static/stable/{{ ansible_architecture }}/docker-{{ docker_version }}.tgz"
        dest: /usr/bin
        remote_src: yes
        extra_opts: [ --strip-components=1 ]
        owner: root
        group: root

    - name: Ensure directories exists
      ansible.builtin.file:
        path: "{{ item }}"
        recurse: yes
        state: directory
      loop:
        - /etc/docker
        - /etc/iptables

    - name: Copy files
      ansible.builtin.copy:
        src: "{{ item }}"
        dest: "/{{ item }}"
        mode: 0755
      loop:
        - etc/init.d/docker
        - etc/docker/daemon.json
        - etc/iptables/ip6tables.rules
        - etc/iptables/iptables.rules
        - etc/ethertypes

    - name: Start docker service
      ansible.builtin.service:
        name: docker
        state: started
        enabled: yes

- name: Install docker-compose
  tags:
    - docker
    - docker_install
    - docker_compose_install
  block:
    - name: Download and install docker-compose
      ansible.builtin.get_url:
        url: "https://github.com/docker/compose/releases/download/{{ docker_compose_version }}/docker-compose-linux-{{ ansible_architecture }}"
        dest: /usr/bin/docker-compose
        group: docker
        mode: 0755

- name: Configure docker
  tags:
    - docker
    - docker_install
    - docker_configure
  block:
    - name: Add system users to docker group
      ansible.builtin.user:
        name: '{{ item }}'
        groups: docker
        append: yes
      loop: "{{ docker_users }}"

    - name: Add custom users to docker group
      ansible.builtin.user:
        name: '{{ item }}'
        groups: docker
        append: yes
      loop: "{{ docker_custom_users }}"
